version: '3.8'
services:
  app:
    build:
      context: spring-backend/
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "5000:5000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bytesynergy
      SPRING_DATASOURCE_USERNAME: ramsai
      SPRING_DATASOURCE_PASSWORD: ramsai@1
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bytesynergy
      MYSQL_USER: ramsai
      MYSQL_PASSWORD: ramsai@1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
