server:
  port: 5000

spring:

  datasource:

    url: jdbc:mysql://localhost:3306/bytesynergy
    username: 
    password: 
    
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  servlet:
    multipart:
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 10MB
      # Max Request Size
      max-request-size: 15MB

springdoc:
  swagger-ui:
    path: /docs

digitalSamba: 
  teamId: 

  developerKey: 

cohereAi:
  Key: 




